### ISSUE TITLE
Unique Names for 4 most important Model collections

### ISSUE THREAD

**Issue by DanRathbun** [stevensrmiller/SketchUpFactory#1]
There is a routine (at least in the SketchUp core) that searches collections for the next valid keyname with the old name suffix, a pound and an integer starting with 1. If a member exists, the integer is increment and the collection is searched again. This repeats until a valid unique Name is found to use for the new collection member.
`"Exterior Door - Fancy#1"`

This routine is called for collections that require a unique name as the key and happens when the user manually right-clicks and chooses "Make Unique" for group or component instances, or whenever some object is chosen from a extra-model resource library, and one of the same name already exists. Or the new member comes into the model via import of a SKP file (from local disk or the 3D Warehouse.)

Entity types that this may occur with include **Components**, **Materials**, **Layers**, and **Scene Pages**. (Unity may not care about the last.)

There happens a scenario when a component or material name has already been differenced with a pound+numeral and it gets cloned and the routine appends an underscore and then another pound sign and repeats the process looking for a numeral suffix then will make the named collection member unique. (Users tend to hate these ugly numbered names.) Ie ...
`"Exterior Door - Fancy#2_#1"`

I'm not sure if the C API exposes this function or not. Shouldn't be too hard to implement using iterators of your dictionary interfaces.

**Comment by stevensrmiller** [comment]
We will have to give this some collective thought, I think. I have had one heck of a time coping with those SketchUp-generated numbers after importing into Unity, as Unity has its own ideas about sorting, uniqueness, and how to auto-generate names. If we add an auto-generated name function (and you're right, it may not be in the C API, but somewhere else; I don't recall seeing one there), I'd like to consider having it operate in different modes, so it is most compatible with the user's needs (pure SketchUp, for importing into Unity, etc.).
