### ISSUE TITLE
Entity subclasses have public constructors

### ISSUE THREAD

**Issue by DanRathbun** [stevensrmiller/SketchUpFactory#4]
### Entity subclasses have public constructors

There are only 3\* SketchUp OOP API classes that expose `new` constructors and these are "helper" classes derived directly from `Object` (or `base` in C#.)

These are ... `Camera`, `Color` and  `ImageRep`
(\*Omitting `UI` class objects from the discussion.) The first two are like little structs. The last is more complex but can hang around unattached as it can be used for virtual things and then discarded having never been used to set the texture of a material, etc.

All the rest, ie, all the collection class instances that belong to the model object, are gotten by asking the model object for a reference, via getter methods. All these collections are singleton objects internally created and attached to the model.
In an OOP layer a coder never calls: `matls = Sketchup.Materials.new();`
Instead they call: `matls = model.Materials;`

Then each collection class has it's **own** factory method(s)... (usually 1, but `Entities` has many for geometry,) ... that create member instance objects that are bound to the collection, and therefor the model.
We never call: `matl1 = Sketchup.Material.new("Pastel Green");`
Instead we call: `matl1 = model.Materials.add("Pastel Green");`

Likewise in an OOP layer use we'd never instantiate a layer that is floating around unattached to an existing Layers collection of a model. The same holds true for all the entity types, and drawing element types (ie, the geometry.)

**Comment by stevensrmiller** [comment]
We can return to this if it becomes a problem.
